### ISSUE TITLE
Symlink not creating (file not found)

### ISSUE THREAD

**Issue by thesoulpole** [360manu/kettlerUSB2BLE#9]
Hello, after completing steps described in issue KettlerUSB port not open
2 - I also tried to go through the steps “automatic launch with the raspberry”
BUT when I try to create the symlink “sudo systemctl link /home/pi/kettlerUSB2BLE/kettler.service”
It does not find the file ("Failed to link unit: No such file or directory"), and in fact it is true - that folder does NOT contain a file kettler.service.

Thanks for any help and explanation!

**Comment by MailFranzel** [comment]
I think this service file is missing. I start the system my hand ...
Step by Step
cd kettlerUSB2BLE
sudo nano server.js
Then I see in the console what is going on; Sometimes I have to restart the server -> I just pressed crtl C

**Comment by thesoulpole** [comment]
Emmanuel
Since I have it working, I wanted to have the Pi startup without peripherals. (then I can just have it attached to the bike like a dongle, with only the power source)
So for that I understand I need to create the symlink (to kettler.service) and then enable it (so it auto-runs at startup).
But the unit file (kettler.service) is not in your repo, and for a newbie (=me), writing one is going to take forever.
Any chance you have it?

**Comment by 360manu** [comment]
Hello

Good to hear that it’s helpfull
I’ll have a look tonight and will keep you posted

Le ven. 9 oct. 2020 à 00:19, Piotr Sienkiewicz <notifications@github.com> a
écrit :

**Comment by 360manu** [comment]
hello

the file is now on the repo

**Comment by thesoulpole** [comment]
thx! 
I will try it out in a bit (tomorrow)

**Comment by thesoulpole** [comment]
Ok, I tested it. 
There is a typo in your file, in the spelling of the path of the WorkingDirectory. You have a capital K and a missing "2BLE" in it. (so the whole service does not start)
(its WorkingDirectory=/home/pi/KettlerUSB in your file)
I corrected it in my local copy and now it starts, and connects to the bike (but I believe I have some problem with the web server - not reading/displaying the data, I will check this further)

**Comment by moonwalker137** [comment]
i had the same issue but after changing in the kettle.service the WorkingDirectory=/home/pi/kettlerUSB2BLE this issue is gone, but I still do not have connection to the bike and not bluetooth available.
